accounts/urls.py
from django.urls import path

from .views import SignUpView, session_login

urlpatterns = [
    path("signup/", SignUpView.as_view(), name="signup"),
    path('login/', session_login, name="login")
]

g_kamp_app/urls.py
from django.urls import path
from . import views

app_name = 'g_kamp_app'
urlpatterns = [
    path('', views.home, name='home'),
    path('search/', views.search, name='search'),
    path('campground/<int:facilityID>/<int:index>', views.campground, name='campground'),
    path('getsessiondata/', views.getSessionData, name='getsessiondata'),
    path('save/', views.savedCampground, name='saved'),
    path('profile/', views.profile, name='profile'),
    path('pro_search/<int:facilityID>/', views.pro_search, name='pro_search'),
    path('campsites/<int:facilityID>/', views.campsites, name='campsites')
]

g_kamp_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView


urlpatterns = [
    path('admin/', admin.site.urls),
    path("", TemplateView.as_view(template_name="home.html"), name="home"),
    path('', include('g_kamp_app.urls')),
    path("accounts/", include("accounts.urls")),
    path("accounts/", include("django.contrib.auth.urls"))
    
]

accounts/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

class CustomUser(AbstractUser):
    session_key = models.CharField(max_length=200) # Saves session key to allow the session data the user has created is recallable.

    def __str__(self):
        return self.username
    

g_kamp_app/models.py
from django.db import models

class Saved(models.Model):
    user = models.ForeignKey('accounts.CustomUser', related_name="saved", on_delete=models.CASCADE)
    saved_date = models.DateTimeField(auto_now_add=True)
    campground = models.CharField(max_length=200)
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.campground

    class Meta:
        ordering = ['-saved_date']
    

accounts/forms.py
from django import forms 
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.sessions.backends.db import SessionStore
from .models import CustomUser

class CustomUserCreationForm(UserCreationForm):

    class Meta:
        model = CustomUser
        fields = ('username', 'email')
    
    # Over rides and adds on session key into the users saved information at the time of signup.
    def save(self, commit=True):
        user = super().save(commit=False)
        user_session = SessionStore()
        user_session.create()
        user.session_key = user_session.session_key
        if commit:
            user.save()
        return user

class CustomUserChangeForm(UserChangeForm):

    class Meta:
        model = CustomUser
        fields = ('username', 'email')

accounts/views.py
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView
from django.contrib.auth import authenticate, login
from .forms import CustomUserCreationForm
from django.shortcuts import render
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.sessions.backends.db import SessionStore

class SignUpView(CreateView):
    form_class = CustomUserCreationForm
    success_url = reverse_lazy("login")
    template_name = "registration/signup.html"

'''
Created a override to Django's base login.
This allows the user's session data to be restored everytime they login.
Restores session data even if Cookies has been cleared.
'''
def session_login(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username = username, password = password)
        if user is not None:
            login(request, user)
            # session = SessionStore(session_key = user.session_key)
            # request.session = session
            return HttpResponseRedirect(reverse_lazy('home'))
        else:
            return HttpResponseRedirect(reverse_lazy('signup'))
    else:
        return render(request, 'registration/login.html')

g_kamp_app/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
import requests
from django.urls import reverse
from .models import Saved

def home(request):
    return render(request, 'home.html')

def search(request):
    states = {
        "AL": 'Alabama', 
        "AK": 'Alaska',
        "AZ": 'Arizona',
        "AR": 'Arkansas',
        "CA": 'California',
        "CO": 'Colorado',
        "CT": 'Connecticut',
        "DE": 'Delaware',
        "DC": 'District Of Columbia',
        "FL": 'Florida',
        "GA": 'Georgia',
        "HI": 'Hawaii',
        "ID": 'Idaho',
        "IL": 'Illinois',
        "IN": 'Indiana',
        "IA": 'Iowa',
        "KS": 'Kansas',
        "KY": 'Kentucky',
        "LA": 'Louisiana',
        "ME": 'Maine',
        "MD": 'Maryland',
        "MA": 'Massachusetts',
        "MI": 'Michigan',
        "MN": 'Minnesota',
        "MS": 'Mississippi',
        "MO": 'Missouri',
        "MT": 'Montana',
        "NE": 'Nebraska',
        "NV": 'Nevada',
        "NH": 'New Hampshire',
        "NJ": 'New Jersey',
        "NM": 'New Mexico',
        "NY": 'New York',
        "NC": 'North Carolina',
        "ND": 'North Dakota',
        "OH": 'Ohio',
        "OK": 'Oklahoma',
        "OR": 'Oregon',
        "PA": 'Pennsylvania',
        "RI": 'Rhode Island',
        "SC": 'South Carolina',
        "SD": 'South Dakota',
        "TN": 'Tennessee',
        "TX": 'Texas',
        "UT": 'Utah',
        "VT": 'Vermont',
        "VA": 'Virginia',
        "WA": 'Washington',
        "WV": 'West Virginia',
        "WI": 'Wisconsin',
        "WY": 'Wyoming',
    }
    limits = request.GET.get('limits', 1)
    state = request.GET.get('state', None)
    page = request.GET.get('current_offset', 0)
    params = {
        'apikey': 'dfed6d80-0ffe-4284-ac92-91a0fc1b901b',
        'limit': limits,
        'offset': page,
        'state': state,
        'activity': 'camping'
    }
    data = requests.get('https://ridb.recreation.gov/api/v1/facilities', params= params).json()
    request.session['data'] = data # Using sessions to allow data to pass between different views.
    return render(request, 'search.html', {'data': data, 'current_offset': page, 'limits': limits, 'state': state, 'states': states})

def campground(request, facilityID, index): # FacilityID and index are passed in from the url to be used as data point in this API call.
    if "data" not in request.session:
        return HttpResponseRedirect(reverse('g_kamp_app:home'))
    data = request.session['data']
    page = request.GET.get('offset', 0)
    params = {
        'limit': 24,
        'offset': page
    }
    campsites = requests.get(f'https://ridb.recreation.gov/api/v1/facilities/{facilityID}/campsites?apikey=dfed6d80-0ffe-4284-ac92-91a0fc1b901b', params = params).json()
    return render(request, 'campground.html', {'campsites':campsites, 'data': data['RECDATA'][index], 'params':params, 'offset': page, 'index': index})

def getSessionData(request): # Using this to get the data from the API calls into Json information so it can be passed into JavaScript.
    data = request.session['data']
    return JsonResponse(data)

def savedCampground(request):
    if request.user.is_authenticated == True:
        campground = request.GET.get('campground')
        name= request.GET.get('name')
        Saved.objects.create(campground = campground, user = request.user, name=name)
        return JsonResponse({'message': 'Saved Campground'})
    else:
        return HttpResponseRedirect(reverse('login'))

def profile(request):
    saved_data = Saved.objects.filter(user=request.user)
    # data = request.session['data']
    return render(request, 'profile.html', {'saved_data':saved_data})

def pro_search(request, facilityID):
    data = requests.get(f'https://ridb.recreation.gov/api/v1/facilities/{facilityID}?apikey=dfed6d80-0ffe-4284-ac92-91a0fc1b901b').json()
    print(data)
    request.session['saved'] = data
    return render(request, 'pro_search.html', {'data': data})

def campsites(request, facilityID):
    saved = request.session['saved']
    page = request.GET.get('offset', 0)
    params = {
        'limit': 24,
        'offset': page
    }
    campsites = requests.get(f'https://ridb.recreation.gov/api/v1/facilities/{facilityID}/campsites?apikey=dfed6d80-0ffe-4284-ac92-91a0fc1b901b', params = params).json()
    return render(request, 'campsites.html', {'campsites': campsites, 'data': saved, 'params':params, 'offset': page,})

g_kamp_app/templates/home.html
{% extends 'index.html' %}

{% block content %}

    <form action="{% url 'g_kamp_app:search' %}" method="get">
        {% csrf_token %}
        <input id='limits' value="limits" type='number' name='limits' placeholder='max 50'>
        <select id='state' value="state" name='state'>
            <option value="AL">Alabama</option>
            <option value="AK">Alaska</option>
            <option value="AZ">Arizona</option>
            <option value="AR">Arkansas</option>
            <option value="CA">California</option>
            <option value="CO">Colorado</option>
            <option value="CT">Connecticut</option>
            <option value="DE">Delaware</option>
            <option value="DC">District Of Columbia</option>
            <option value="FL">Florida</option>
            <option value="GA">Georgia</option>
            <option value="HI">Hawaii</option>
            <option value="ID">Idaho</option>
            <option value="IL">Illinois</option>
            <option value="IN">Indiana</option>
            <option value="IA">Iowa</option>
            <option value="KS">Kansas</option>
            <option value="KY">Kentucky</option>
            <option value="LA">Louisiana</option>
            <option value="ME">Maine</option>
            <option value="MD">Maryland</option>
            <option value="MA">Massachusetts</option>
            <option value="MI">Michigan</option>
            <option value="MN">Minnesota</option>
            <option value="MS">Mississippi</option>
            <option value="MO">Missouri</option>
            <option value="MT">Montana</option>
            <option value="NE">Nebraska</option>
            <option value="NV">Nevada</option>
            <option value="NH">New Hampshire</option>
            <option value="NJ">New Jersey</option>
            <option value="NM">New Mexico</option>
            <option value="NY">New York</option>
            <option value="NC">North Carolina</option>
            <option value="ND">North Dakota</option>
            <option value="OH">Ohio</option>
            <option value="OK">Oklahoma</option>
            <option value="OR">Oregon</option>
            <option value="PA">Pennsylvania</option>
            <option value="RI">Rhode Island</option>
            <option value="SC">South Carolina</option>
            <option value="SD">South Dakota</option>
            <option value="TN">Tennessee</option>
            <option value="TX">Texas</option>
            <option value="UT">Utah</option>
            <option value="VT">Vermont</option>
            <option value="VA">Virginia</option>
            <option value="WA">Washington</option>
            <option value="WV">West Virginia</option>
            <option value="WI">Wisconsin</option>
            <option value="WY">Wyoming</option>
            {% comment %} {% for key, name in states.items%}
                {% if key == state %}
                    <option selected value="{{ key }}">{{ name }}</option>
                {% else %}
                    <option value="{{ key }}">{{ name }}</option>
                {% endif %}
            {% endfor %} {% endcomment %}
        </select>
        <button type='submit'>Search</button>
    </form>
    
    {% comment %} <form action="{% url g_kamp_app:campground %}" method="get"> {% endcomment %}
        {% comment %} {% csrf_token %}
        {% for i in RECDATA.RECDATA %}
            <h2><a href="campground/{{ i.FacilityID }}">{{ i.FacilityName }}</a> -- {{ i.FacilityID }}</h2>
        {% endfor %} {% endcomment %}
    {% comment %} </form> {% endcomment %}

    
{% endblock content %}

g_kamp_app/templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% comment %} <form action="{% url 'g_kamp_app:search' %}" method="get">
        {% csrf_token %}
        <input id='limits' value="limits" type='number' name='limits' placeholder='max 50'>
        <select id='state' value="state" name='state'>
            <option value="AL">Alabama</option>
            <option value="AK">Alaska</option>
            <option value="AZ">Arizona</option>
            <option value="AR">Arkansas</option>
            <option value="CA">California</option>
            <option value="CO">Colorado</option>
            <option value="CT">Connecticut</option>
            <option value="DE">Delaware</option>
            <option value="DC">District Of Columbia</option>
            <option value="FL">Florida</option>
            <option value="GA">Georgia</option>
            <option value="HI">Hawaii</option>
            <option value="ID">Idaho</option>
            <option value="IL">Illinois</option>
            <option value="IN">Indiana</option>
            <option value="IA">Iowa</option>
            <option value="KS">Kansas</option>
            <option value="KY">Kentucky</option>
            <option value="LA">Louisiana</option>
            <option value="ME">Maine</option>
            <option value="MD">Maryland</option>
            <option value="MA">Massachusetts</option>
            <option value="MI">Michigan</option>
            <option value="MN">Minnesota</option>
            <option value="MS">Mississippi</option>
            <option value="MO">Missouri</option>
            <option value="MT">Montana</option>
            <option value="NE">Nebraska</option>
            <option value="NV">Nevada</option>
            <option value="NH">New Hampshire</option>
            <option value="NJ">New Jersey</option>
            <option value="NM">New Mexico</option>
            <option value="NY">New York</option>
            <option value="NC">North Carolina</option>
            <option value="ND">North Dakota</option>
            <option value="OH">Ohio</option>
            <option value="OK">Oklahoma</option>
            <option value="OR">Oregon</option>
            <option value="PA">Pennsylvania</option>
            <option value="RI">Rhode Island</option>
            <option value="SC">South Carolina</option>
            <option value="SD">South Dakota</option>
            <option value="TN">Tennessee</option>
            <option value="TX">Texas</option>
            <option value="UT">Utah</option>
            <option value="VT">Vermont</option>
            <option value="VA">Virginia</option>
            <option value="WA">Washington</option>
            <option value="WV">West Virginia</option>
            <option value="WI">Wisconsin</option>
            <option value="WY">Wyoming</option>
            {% for key, name in states.items%}
                {% if key == state %}
                    <option selected value="{{ key }}">{{ name }}</option>
                {% else %}
                    <option value="{{ key }}">{{ name }}</option>
                {% endif %}
            {% endfor %} 
        </select>
        {% if current_offset == 0%}
        <button type='submit'>Search</button>
        {% else %}
            <button id='pageBack' type='submit'>Previous Page</button>
            <button type='submit'>Next Page</button>
        {% endif %}
        

        <button type='submit'>
            {% if current_offset == 0%}
                Search
            {% else %}
                View Next Page
            {% endif %}
        </button>
        <input id='current_offset' value='{{ current_offset|add:limits }}' type='hidden' name="current_offset">
        <button id='reset'>Reset</button>
    </form> {% endcomment %}
    
    {% comment %} <form action="{% url g_kamp_app:campground %}" method="get"> {% endcomment %}
        {% comment %} {% csrf_token %}
        {% for i in RECDATA.RECDATA %}
            <h2><a href="campground/{{ i.FacilityID }}">{{ i.FacilityName }}</a> -- {{ i.FacilityID }}</h2>
        {% endfor %} {% endcomment %}
    {% comment %} </form> {% endcomment %}

    {% block content %}
    {% endblock content %}

    <script>
        {% comment %} JS for reset button on search page. {% endcomment %}
        let reset = document.querySelector('#reset')
        reset.addEventListener('click', function(){
            document.getElementById("limits").value = 1
            document.getElementById("state").value = null
            document.getElementById("current_offset").value = 0
        })
        {% comment %} JS for backbutton logic on search page. {% endcomment %}
        let pageBack = document.querySelector('#pageBack')
        pageBack.addEventListener('click', function(){
            let limits = document.getElementById('limits').value
            let current_offset = document.getElementById('current_offset').value
            console.log(current_offset)
            document.getElementById('current_offset').value = current_offset - (limits*2)
        })
    </script>
</body>
</html>

g_kamp_app/templates/search.html
{% extends 'home.html' %}

{% block content %}
<form action="{% url 'g_kamp_app:search' %}" method="get">
        {% csrf_token %}
        <input id='limits' value="{{ limits }}" type='number' name='limits' placeholder='max 50'>
        <select id='state' value="{{ state }}" name='state'>
            {% for key, name in states.items%}
                {% if key == state %}
                    <option selected value="{{ key }}">{{ name }}</option>
                {% else %}
                    <option value="{{ key }}">{{ name }}</option>
                {% endif %}
            {% endfor %}
        </select>
        {% comment %} {% if current_offset == 0%}
            <button type='submit'>Search</button>
        {% else %} {% endcomment %}
            <button id='pageBack' type='submit'>Previous Page</button>
            <button type='submit'>Next Page</button>
        {% comment %} {% endif %} {% endcomment %}
        <input id='current_offset' value='{{ current_offset|add:limits }}' type='hidden' name="current_offset">
        <button id='reset'>Reset</button>
    </form>

    {% for i in RECDATA.RECDATA %}
        <h2><a href="campground/{{ i.FacilityID }}">{{ i.FacilityName }}</a> -- {{ i.FacilityID }}</h2>
    {% endfor %}

{% endblock content %}

templates/search.html
{% extends 'index.html' %}

{% block content %}

{% comment %} Form has saved data from initial search on the home page {% endcomment %}
{% if data.RECDATA%}
    <form action="{% url 'g_kamp_app:search' %}" method="get">
        {% csrf_token %}
        <div class='row'>
            <div class='input-field col s6 m6'>
                <input id='limits' value="{{ limits }}" type='number' name='limits' placeholder='max 50'>
            </div>
            <div class="input-field col s6 m6">
                <select id='state' value="{{ state }}" name='state'>
{% comment %} For loop to that gets state data from states variable that is saved in the search view {% endcomment %}
                    {% for key, name in states.items%}
                        {% if key == state %}
                            <option selected value="{{ key }}">{{ name }}</option>
                        {% else %}
                            <option value="{{ key }}">{{ name }}</option>
                        {% endif %}
                    {% endfor %}
                </select>
            </div>
        </div>
        <button style="margin-left: 1em; margin-bottom: 2em" id='pageBack' type='submit'>Previous Page</button>
        <button type='submit'>Next Page/New Search</button>
        <input id='current_offset' value='{{ current_offset|add:limits }}' type='hidden' name="current_offset">         {% comment %} Allows the next page funcionality by taking the current offset in the api call and adding the limit to it to get the next set of data from the search. {% endcomment%}
        {% comment %} <a id='reset' href="..">Reset</a> {% endcomment %}
    </form>
{% endif %}

{% comment %} Sets location and size of map. {% endcomment %}
    <div id="map" class="center-align" style="width: 100%; height: 600px; position: relative; al"></div>

{% comment %} Parsing through the data from the API call to get the info to display. {% endcomment %}
    <div class='row'>
        {% for i in data.RECDATA %}
        <div class='col s12 m4 l4'>
            <div class='card small deep-purple lighten-4'>
                <div class='card-content white text'>
                    <span class='card-title'><a href="{% url 'g_kamp_app:campground' i.FacilityID forloop.counter0 %}">{{ i.FacilityName }}</a></span>  {% comment %} Makes the facility name a hyperlink to its campground info with its campsites displayed. {% endcomment %}
                    {% if i.FacilityPhone == '' %}
                    {% else %}
                        <p>Phone: {{ i.FacilityPhone }}</p>
                    {% endif %}
                    {% if i.FacilityEmail == '' %}
                    {% else %}
                        <p>Email: {{ i.FacilityEmail }}</p>
                    {% endif %}
                </div>
                <div class='card-action'>
                    <button id='{{ i.FacilityID }}' name='{{ i.FacilityName }}' class='save_button'>Save</button>
                </div>
            </div>
        </div>    
        {% endfor %}
    </div>

    <script>
{% comment %} JavaScript for save funcionality saving the campground ID and name to allow to be call back if cookies gets cleared, clearing the session data. {% endcomment %}
        let buttons = document.querySelectorAll('.save_button')
        buttons.forEach(button => {
            button.addEventListener('click', (event)=> saved(event))
        })
        function saved(event){
            event.preventDefault()
            campground = event.target.id
            name = event.target.name
            axios({
                method: 'get',
                url: '{% url "g_kamp_app:saved" %}',
                params: {
                    campground,
                    name
                }
            }).then((data) =>{
                alert('Campground saved!')
            })
        }

{% comment %} stateInfo pulls the specific state from the search. {% endcomment %}
        let stateInfo = document.getElementById('state').value

{% comment %} state contains the lat/long data plus zoom amount for mapping. {% endcomment %}
        let states = {
            "AL": {"name":'Alabama', 'lat': 32.618231, 'long': -86.902298, 'zoom': 7},
            "AK": {'name':'Alaska', 'lat': 63.588753, 'long': -154.493062, 'zoom': 4},
            "AZ": {'name':'Arizona', 'lat': 34.048928, 'long': -111.093731, 'zoom': 7},
            "AR": {'name':'Arkansas', 'lat': 35.20105, 'long': -91.831833, 'zoom': 7},
            "CA": {'name':'California', 'lat': 36.778261, 'long': -119.417932, 'zoom': 5},
            "CO": {'name':'Colorado', 'lat': 39.0051, 'long': -105.782067, 'zoom': 7},
            "CT": {'name':'Connecticut', 'lat': 41.603221, 'long': -73.087749, 'zoom': 8},
            "DE": {'name':'Delaware', 'lat': 38.910832, 'long': -75.52767, 'zoom': 8},
            "DC": {'name':'District Of Columbia', 'lat': 38.905985, 'long': -77.033418, 'zoom': 9},
            "FL": {'name':'Florida', 'lat': 27.664827, 'long': -81.515754, 'zoom': 6},
            "GA": {'name':'Georgia', 'lat': 32.67435, 'long': -82.907123, 'zoom': 7},
            "HI": {'name':'Hawaii', 'lat': 19.898682, 'long': -155.665857, 'zoom': 6},
            "ID": {'name':'Idaho', 'lat': 45.068202, 'long': -114.742041, 'zoom': 6},
            "IL": {'name':'Illinois', 'lat': 40.633125, 'long': -89.398528, 'zoom': 7},
            "IN": {'name':'Indiana', 'lat': 40.551217, 'long': -85.602364, 'zoom': 7},
            "IA": {'name':'Iowa', 'lat': 41.878003, 'long': -93.097702	, 'zoom': 7},
            "KS": {'name':'Kansas', 'lat': 39.011902, 'long': -98.484246, 'zoom': 7},
            "KY": {'name':'Kentucky', 'lat': 37.839333, 'long': -84.270018, 'zoom': 7},
            "LA": {'name':'Louisiana', 'lat': 31.244823, 'long': -92.145024, 'zoom': 7},
            "ME": {'name':'Maine', 'lat': 45.253783, 'long': -69.445469, 'zoom': 7},
            "MD": {'name':'Maryland', 'lat': 39.045755, 'long': -76.641271, 'zoom': 8},
            "MA": {'name':'Massachusetts', 'lat': 42.407211, 'long': -71.382437, 'zoom': 8},
            "MI": {'name':'Michigan', 'lat': 44.314844, 'long': -85.602364, 'zoom': 6},
            "MN": {'name':'Minnesota', 'lat': 46.729553, 'long': -94.6859, 'zoom': 7},
            "MS": {'name':'Mississippi', 'lat': 32.554668, 'long': -89.398528, 'zoom': 7},
            "MO": {'name':'Missouri', 'lat': 37.964253, 'long': -91.831833, 'zoom': 7},
            "MT": {'name':'Montana', 'lat': 46.879682, 'long': -110.362566, 'zoom': 6},
            "NE": {'name':'Nebraska', 'lat': 41.492537, 'long': -99.901813, 'zoom': 7},
            "NV": {'name':'Nevada', 'lat': 38.80261, 'long': -116.419389, 'zoom': 7},
            "NH": {'name':'New Hampshire', 'lat': 43.193852, 'long': -71.572395, 'zoom': 8},
            "NJ": {'name':'New Jersey', 'lat': 40.058324, 'long': -74.405661, 'zoom': 8},
            "NM": {'name':'New Mexico', 'lat': 34.97273, 'long': -105.032363, 'zoom': 7},
            "NY": {'name':'New York', 'lat': 43.299428, 'long': -74.217933, 'zoom': 7},
            "NC": {'name':'North Carolina', 'lat': 35.759573, 'long': -79.0193, 'zoom': 7},
            "ND": {'name':'North Dakota', 'lat': 47.551493, 'long': -101.002012, 'zoom': 7},
            "OH": {'name':'Ohio', 'lat': 40.417287, 'long': -82.907123, 'zoom': 7},
            "OK": {'name':'Oklahoma', 'lat': 35.007752, 'long': -97.092877, 'zoom': 7},
            "OR": {'name':'Oregon', 'lat': 43.804133, 'long': -120.554201, 'zoom': 7},
            "PA": {'name':'Pennsylvania', 'lat': 41.203322, 'long': -77.194525, 'zoom': 7},
            "RI": {'name':'Rhode Island', 'lat': 41.580095, 'long': -71.477429, 'zoom': 9},
            "SC": {'name':'South Carolina', 'lat': 33.836081, 'long': -81.163725, 'zoom': 7},
            "SD": {'name':'South Dakota', 'lat': 43.969515, 'long': -99.901813, 'zoom': 7},
            "TN": {'name':'Tennessee', 'lat': 35.517491, 'long': -86.580447, 'zoom': 7},
            "TX": {'name':'Texas', 'lat': 31.568599, 'long': -99.901813, 'zoom': 6},
            "UT": {'name':'Utah', 'lat': 39.52098, 'long': -111.093731, 'zoom': 7},
            "VT": {'name':'Vermont', 'lat': 44.558803, 'long': -72.577841, 'zoom': 8},
            "VA": {'name':'Virginia', 'lat': 37.431573, 'long': -78.656894, 'zoom': 7},
            "WA": {'name':'Washington', 'lat': 47.751074, 'long': -120.740139, 'zoom': 7},
            "WV": {'name':'West Virginia', 'lat': 38.597626, 'long': -80.454903, 'zoom': 7},
            "WI": {'name':'Wisconsin', 'lat': 43.78444, 'long': -88.787868, 'zoom': 7},
            "WY": {'name':'Wyoming', 'lat': 43.075968, 'long': -107.290284, 'zoom': 7},
        }

{% comment %} Call the getsessiondata function in the views.py to get the data for the campgrounds {% endcomment %}
       axios({
            method: 'get',
            url: '{% url "g_kamp_app:getsessiondata" %}'
       }).then((data) => {
            
       
{% comment %} USA Central cordanance 37.0902, -95.7129 for if I can get the map animiation to work at some point. {% endcomment %}

{% comment %} Initializing map with data point from the state being searched. {% endcomment %}

            var map = L.map('map').setView([states[stateInfo].lat, states[stateInfo].long], states[stateInfo].zoom)

            var tiles = L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png', {
                maxZoom: 19,
                attribution: '&copy; <a href="http://www.openstreetmap.org/copyright">OpenStreetMap</a>'
            }).addTo(map);
             {% comment %} map.flyTo([states[stateInfo].lat, states[stateInfo].long], states[stateInfo].zoom, {animate:true, duration:1.5} )  {% endcomment %}

{% comment %} Creates the markers and displays the facility data when marker is clicked on.  Plus has a hyperlink as the name as well. {% endcomment %}

            for (let [index, mark] of data.data.RECDATA.entries()){
                let markLat = mark.FacilityLatitude
                let markLong = mark.FacilityLongitude
                let marker = L.marker([markLat, markLong]).addTo(map)
                marker.bindPopup(`<a href = "../campground/${mark.FacilityID}/${index}">${mark.FacilityName}</a> -- ${mark.FacilityID}`)
            }
        })
    </script>

{% endblock content %}